### ISSUE TITLE
Mist主题默认使图片居中

### ISSUE THREAD

**Issue by utouch** [utouch/utouch.github.io#5]
在全局样式中有

``` css
.post-body img { margin: 0; }
```

> /themes/next/source/css/_schemes/Mist/_posts-expanded.styl - Line 30
> 这样的代码，解析出来之后是这个样子的：

``` css
.posts-expand .post-body img {
  margin: 0;
}
```

修改为即可

``` css
.post-body img { margin: 0 auto; }
```

或者试下这种修改
https://github.com/iissnan/hexo-theme-next/issues/910
